--------------------------------------------------------

--  파일이 생성됨 - 토요일-12월-31-2022   

--------------------------------------------------------

--------------------------------------------------------

--  DDL for Table MEMBERS

--------------------------------------------------------


  CREATE TABLE "BOOK_EX"."MEMBERS" 
   (	"MEMBER_ID" NUMBER(10,0), 
	"MEMBER_IDID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(20 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_SEX" NUMBER(1,0), 
	"MEMBER_PHONE" VARCHAR2(30 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(30 BYTE), 
	"MEMBER_ADDRESS1" VARCHAR2(30 BYTE), 
	"MEMBER_ADDRESS2" VARCHAR2(30 BYTE), 
	"MEMBER_POSTNUM" NUMBER(8,0), 
	"MEMBER_GRADE" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

REM INSERTING into BOOK_EX.MEMBERS

SET DEFINE OFF;

Insert into BOOK_EX.MEMBERS (MEMBER_ID,MEMBER_IDID,MEMBER_PW,MEMBER_NAME,MEMBER_SEX,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_POSTNUM,MEMBER_GRADE) values (1,'isshosng','2709','최태승',1,'+82 10-8579-2709','oneheal57@gmail.com','강릉시 내곡동','서울특별시 도봉구',1455,'admin');

Insert into BOOK_EX.MEMBERS (MEMBER_ID,MEMBER_IDID,MEMBER_PW,MEMBER_NAME,MEMBER_SEX,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_POSTNUM,MEMBER_GRADE) values (2,'222','9607','이세은',2,'+82 1234-5678','email','서울특별시 도봉구','서울특별시 도봉구',1337,'client');

--------------------------------------------------------

--  DDL for Index MEMBERS_PK

--------------------------------------------------------


  CREATE UNIQUE INDEX "BOOK_EX"."MEMBERS_PK" ON "BOOK_EX"."MEMBERS" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------

--  Constraints for Table MEMBERS

--------------------------------------------------------


  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_IDID" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_SEX" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_ADDRESS2" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_POSTNUM" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" MODIFY ("MEMBER_GRADE" NOT NULL ENABLE);
  ALTER TABLE "BOOK_EX"."MEMBERS" ADD CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

